In [13]:
import numpy as np
text = "good morning"
chars = sorted(list(set(text)))
print(chars)

[' ', 'd', 'g', 'i', 'm', 'n', 'o', 'r']


In [14]:
chartoind = {ch:i for i,ch in enumerate(chars)}
indtochar = {i:ch for i,ch in enumerate(chars)}
print(chartoind)
print(indtochar)

{' ': 0, 'd': 1, 'g': 2, 'i': 3, 'm': 4, 'n': 5, 'o': 6, 'r': 7}
{0: ' ', 1: 'd', 2: 'g', 3: 'i', 4: 'm', 5: 'n', 6: 'o', 7: 'r'}


In [15]:
textind = [chartoind[char] for char in text]
print(textind)

[2, 6, 6, 1, 0, 4, 6, 7, 5, 3, 5, 2]


In [16]:
sequLen = 4
X = []
y = []
for pos in range(len(textind)-sequLen):
    X.append(textind[pos:pos+sequLen])
    y.append(textind[pos+sequLen])

print(X)
X = np.array(X)
print(y)
y=np.array(y)

[[2, 6, 6, 1], [6, 6, 1, 0], [6, 1, 0, 4], [1, 0, 4, 6], [0, 4, 6, 7], [4, 6, 7, 5], [6, 7, 5, 3], [7, 5, 3, 5]]
[0, 4, 6, 7, 5, 3, 5, 2]


In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

model = Sequential()
model.add(SimpleRNN(128,input_shape=(X.shape[1],len(chars)),activation="relu"))
model.add(Dense(len(chars),activation="softmax"))
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [18]:
Xencoded = np.zeros((X.shape[0],X.shape[1],len(chars)))
#print(Xencoded)
for i,sequence in enumerate(X):
    #print(sequence)
    for p,character in enumerate(sequence):
        #print(p)
        #print(character)
        Xencoded[i,p,character] = 1

print(Xencoded)

[[[0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]]]


In [19]:
y = np.expand_dims(y,axis=1)
print(y)

[[0]
 [4]
 [6]
 [7]
 [5]
 [3]
 [5]
 [2]]


In [20]:
model.fit(Xencoded,y,epochs=50,batch_size=12)

Epoch 1/50
1/1 [==============================] - 0s 435ms/step - loss: 2.0796 - accuracy: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 3ms/step - loss: 2.0239 - accuracy: 0.1250
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 1.9708 - accuracy: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 3ms/step - loss: 1.9183 - accuracy: 0.6250
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 1.8667 - accuracy: 0.7500
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 1.8149 - accuracy: 0.8750
Epoch 7/50
1/1 [==============================] - 0s 2ms/step - loss: 1.7637 - accuracy: 0.8750
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 1.7132 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 3ms/step - loss: 1.6626 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 3ms/step - loss: 1.6104 - accuracy: 1.0000
Epoch 11/50
1/1 [================

In [28]:
def predict(seed):
    if len(seed)<sequLen:
        seed = seed.rjust(sequLen)
    elif len(seed)>sequLen:
        seed = seed[-sequLen:]

    seedIndex = [chartoind[char] for char in seed]
    Xseed = np.zeros((1,sequLen,len(chars)))
    for pos,index in enumerate(seedIndex):
        Xseed[0,pos,index] = 1
    pred = model.predict(Xseed)
    print(pred)
    pred = np.argmax(pred[0])
    print(pred)
    pred = indtochar[pred]    
    print(pred)


In [33]:
predict("dni gd")

1/1 [==============================] - 0s 13ms/step
[[7.0720389e-02 3.1612843e-04 1.1567911e-01 9.4659396e-02 1.7989002e-02
  1.1501233e-01 5.4788195e-02 5.3083539e-01]]
7
r
